// Generated by gencpp from file msg_pkg/DetectedObject.msg
// DO NOT EDIT!


#ifndef MSG_PKG_MESSAGE_DETECTEDOBJECT_H
#define MSG_PKG_MESSAGE_DETECTEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace msg_pkg
{
template <class ContainerAllocator>
struct DetectedObject_
{
  typedef DetectedObject_<ContainerAllocator> Type;

  DetectedObject_()
    : object_id(0)
    , global_position()  {
    }
  DetectedObject_(const ContainerAllocator& _alloc)
    : object_id(0)
    , global_position(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _object_id_type;
  _object_id_type object_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _global_position_type;
  _global_position_type global_position;





  typedef boost::shared_ptr< ::msg_pkg::DetectedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_pkg::DetectedObject_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObject_

typedef ::msg_pkg::DetectedObject_<std::allocator<void> > DetectedObject;

typedef boost::shared_ptr< ::msg_pkg::DetectedObject > DetectedObjectPtr;
typedef boost::shared_ptr< ::msg_pkg::DetectedObject const> DetectedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_pkg::DetectedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_pkg::DetectedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_pkg::DetectedObject_<ContainerAllocator1> & lhs, const ::msg_pkg::DetectedObject_<ContainerAllocator2> & rhs)
{
  return lhs.object_id == rhs.object_id &&
    lhs.global_position == rhs.global_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_pkg::DetectedObject_<ContainerAllocator1> & lhs, const ::msg_pkg::DetectedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg::DetectedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg::DetectedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg::DetectedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg::DetectedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg::DetectedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg::DetectedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_pkg::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08583d37b8e045278bf90fa68ff7e74d";
  }

  static const char* value(const ::msg_pkg::DetectedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08583d37b8e04527ULL;
  static const uint64_t static_value2 = 0x8bf90fa68ff7e74dULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_pkg::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_pkg/DetectedObject";
  }

  static const char* value(const ::msg_pkg::DetectedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_pkg::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 object_id\n"
"geometry_msgs/Point global_position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::msg_pkg::DetectedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_pkg::DetectedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_id);
      stream.next(m.global_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_pkg::DetectedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_pkg::DetectedObject_<ContainerAllocator>& v)
  {
    s << indent << "object_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.object_id);
    s << indent << "global_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.global_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_PKG_MESSAGE_DETECTEDOBJECT_H
