// Generated by gencpp from file msg_pkg/GetMapCompressed.msg
// DO NOT EDIT!


#ifndef MSG_PKG_MESSAGE_GETMAPCOMPRESSED_H
#define MSG_PKG_MESSAGE_GETMAPCOMPRESSED_H

#include <ros/service_traits.h>


#include <msg_pkg/GetMapCompressedRequest.h>
#include <msg_pkg/GetMapCompressedResponse.h>


namespace msg_pkg
{

struct GetMapCompressed
{

typedef GetMapCompressedRequest Request;
typedef GetMapCompressedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMapCompressed
} // namespace msg_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msg_pkg::GetMapCompressed > {
  static const char* value()
  {
    return "54ee168365956cd5736b351118adcd18";
  }

  static const char* value(const ::msg_pkg::GetMapCompressed&) { return value(); }
};

template<>
struct DataType< ::msg_pkg::GetMapCompressed > {
  static const char* value()
  {
    return "msg_pkg/GetMapCompressed";
  }

  static const char* value(const ::msg_pkg::GetMapCompressed&) { return value(); }
};


// service_traits::MD5Sum< ::msg_pkg::GetMapCompressedRequest> should match
// service_traits::MD5Sum< ::msg_pkg::GetMapCompressed >
template<>
struct MD5Sum< ::msg_pkg::GetMapCompressedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msg_pkg::GetMapCompressed >::value();
  }
  static const char* value(const ::msg_pkg::GetMapCompressedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msg_pkg::GetMapCompressedRequest> should match
// service_traits::DataType< ::msg_pkg::GetMapCompressed >
template<>
struct DataType< ::msg_pkg::GetMapCompressedRequest>
{
  static const char* value()
  {
    return DataType< ::msg_pkg::GetMapCompressed >::value();
  }
  static const char* value(const ::msg_pkg::GetMapCompressedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msg_pkg::GetMapCompressedResponse> should match
// service_traits::MD5Sum< ::msg_pkg::GetMapCompressed >
template<>
struct MD5Sum< ::msg_pkg::GetMapCompressedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msg_pkg::GetMapCompressed >::value();
  }
  static const char* value(const ::msg_pkg::GetMapCompressedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msg_pkg::GetMapCompressedResponse> should match
// service_traits::DataType< ::msg_pkg::GetMapCompressed >
template<>
struct DataType< ::msg_pkg::GetMapCompressedResponse>
{
  static const char* value()
  {
    return DataType< ::msg_pkg::GetMapCompressed >::value();
  }
  static const char* value(const ::msg_pkg::GetMapCompressedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSG_PKG_MESSAGE_GETMAPCOMPRESSED_H
