// Generated by gencpp from file msg_pkg/GetMapCompressedRequest.msg
// DO NOT EDIT!


#ifndef MSG_PKG_MESSAGE_GETMAPCOMPRESSEDREQUEST_H
#define MSG_PKG_MESSAGE_GETMAPCOMPRESSEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_pkg
{
template <class ContainerAllocator>
struct GetMapCompressedRequest_
{
  typedef GetMapCompressedRequest_<ContainerAllocator> Type;

  GetMapCompressedRequest_()
    {
    }
  GetMapCompressedRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapCompressedRequest_

typedef ::msg_pkg::GetMapCompressedRequest_<std::allocator<void> > GetMapCompressedRequest;

typedef boost::shared_ptr< ::msg_pkg::GetMapCompressedRequest > GetMapCompressedRequestPtr;
typedef boost::shared_ptr< ::msg_pkg::GetMapCompressedRequest const> GetMapCompressedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace msg_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_pkg/GetMapCompressedRequest";
  }

  static const char* value(const ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapCompressedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::msg_pkg::GetMapCompressedRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MSG_PKG_MESSAGE_GETMAPCOMPRESSEDREQUEST_H
