// Generated by gencpp from file msg_pkg/ProcessedObjectArray.msg
// DO NOT EDIT!


#ifndef MSG_PKG_MESSAGE_PROCESSEDOBJECTARRAY_H
#define MSG_PKG_MESSAGE_PROCESSEDOBJECTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <msg_pkg/ProcessedObject.h>

namespace msg_pkg
{
template <class ContainerAllocator>
struct ProcessedObjectArray_
{
  typedef ProcessedObjectArray_<ContainerAllocator> Type;

  ProcessedObjectArray_()
    : header()
    , vehicle_position()
    , vehicle_yaw(0.0)
    , objects()  {
    }
  ProcessedObjectArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vehicle_position(_alloc)
    , vehicle_yaw(0.0)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _vehicle_position_type;
  _vehicle_position_type vehicle_position;

   typedef double _vehicle_yaw_type;
  _vehicle_yaw_type vehicle_yaw;

   typedef std::vector< ::msg_pkg::ProcessedObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::msg_pkg::ProcessedObject_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessedObjectArray_

typedef ::msg_pkg::ProcessedObjectArray_<std::allocator<void> > ProcessedObjectArray;

typedef boost::shared_ptr< ::msg_pkg::ProcessedObjectArray > ProcessedObjectArrayPtr;
typedef boost::shared_ptr< ::msg_pkg::ProcessedObjectArray const> ProcessedObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator1> & lhs, const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vehicle_position == rhs.vehicle_position &&
    lhs.vehicle_yaw == rhs.vehicle_yaw &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator1> & lhs, const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2878e3c099337b128953ff448b2966e0";
  }

  static const char* value(const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2878e3c099337b12ULL;
  static const uint64_t static_value2 = 0x8953ff448b2966e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_pkg/ProcessedObjectArray";
  }

  static const char* value(const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point vehicle_position\n"
"float64 vehicle_yaw\n"
"ProcessedObject[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: msg_pkg/ProcessedObject\n"
"int32 object_id\n"
"float64 relative_distance\n"
"int32 risk_level\n"
"geometry_msgs/Point relative_position\n"
"geometry_msgs/Point global_position\n"
;
  }

  static const char* value(const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vehicle_position);
      stream.next(m.vehicle_yaw);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessedObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_pkg::ProcessedObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_pkg::ProcessedObjectArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vehicle_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.vehicle_position);
    s << indent << "vehicle_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.vehicle_yaw);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::msg_pkg::ProcessedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_PKG_MESSAGE_PROCESSEDOBJECTARRAY_H
