(cl:defpackage msg_pkg-srv
  (:use )
  (:export
   "GETMAPCOMPRESSED"
   "<GETMAPCOMPRESSED-REQUEST>"
   "GETMAPCOMPRESSED-REQUEST"
   "<GETMAPCOMPRESSED-RESPONSE>"
   "GETMAPCOMPRESSED-RESPONSE"
  ))

