# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_pkg/ProcessedObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class ProcessedObject(genpy.Message):
  _md5sum = "a5c038ccad5ad73f55b80d3464c5fdb7"
  _type = "msg_pkg/ProcessedObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 object_id
float64 relative_distance
int32 risk_level
geometry_msgs/Point relative_position
geometry_msgs/Point global_position
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['object_id','relative_distance','risk_level','relative_position','global_position']
  _slot_types = ['int32','float64','int32','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_id,relative_distance,risk_level,relative_position,global_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ProcessedObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.object_id is None:
        self.object_id = 0
      if self.relative_distance is None:
        self.relative_distance = 0.
      if self.risk_level is None:
        self.risk_level = 0
      if self.relative_position is None:
        self.relative_position = geometry_msgs.msg.Point()
      if self.global_position is None:
        self.global_position = geometry_msgs.msg.Point()
    else:
      self.object_id = 0
      self.relative_distance = 0.
      self.risk_level = 0
      self.relative_position = geometry_msgs.msg.Point()
      self.global_position = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_idi6d().pack(_x.object_id, _x.relative_distance, _x.risk_level, _x.relative_position.x, _x.relative_position.y, _x.relative_position.z, _x.global_position.x, _x.global_position.y, _x.global_position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.relative_position is None:
        self.relative_position = geometry_msgs.msg.Point()
      if self.global_position is None:
        self.global_position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.object_id, _x.relative_distance, _x.risk_level, _x.relative_position.x, _x.relative_position.y, _x.relative_position.z, _x.global_position.x, _x.global_position.y, _x.global_position.z,) = _get_struct_idi6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_idi6d().pack(_x.object_id, _x.relative_distance, _x.risk_level, _x.relative_position.x, _x.relative_position.y, _x.relative_position.z, _x.global_position.x, _x.global_position.y, _x.global_position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.relative_position is None:
        self.relative_position = geometry_msgs.msg.Point()
      if self.global_position is None:
        self.global_position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.object_id, _x.relative_distance, _x.risk_level, _x.relative_position.x, _x.relative_position.y, _x.relative_position.z, _x.global_position.x, _x.global_position.y, _x.global_position.z,) = _get_struct_idi6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_idi6d = None
def _get_struct_idi6d():
    global _struct_idi6d
    if _struct_idi6d is None:
        _struct_idi6d = struct.Struct("<idi6d")
    return _struct_idi6d
