(cl:defpackage msg_pkg-msg
  (:use )
  (:export
   "<DETECTEDOBJECT>"
   "DETECTEDOBJECT"
   "<DETECTEDOBJECTARRAY>"
   "DETECTEDOBJECTARRAY"
   "<PROCESSEDOBJECT>"
   "PROCESSEDOBJECT"
   "<PROCESSEDOBJECTARRAY>"
   "PROCESSEDOBJECTARRAY"
  ))

